
trigger:
- master

pr:
- master

variables:
  solutionPath: '**\*.sln'

jobs:
- job: build_windows

  pool:
    vmImage: windows-latest
  
  steps:

  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'sonarcloud-TrueFlame42'
      organization: '2006-jun15-net'
      scannerMode: 'MSBuild'
      projectKey: '2006-jun15-net_daniel-project1'
      projectName: 'Daniel project 1 Project1'
  
  - task: NuGetToolInstaller@1
    displayName: install nuget
    inputs:
      versionSpec:

  - task: NuGetCommand@2
    displayName: nuget restore
    inputs:
      command: 'restore'
      restoreSolution: '**/*.sln'
      feedsToUse: 'select'

  - task: VSBuild@1
    displayName: Visual Studio build
    inputs:
      solution: '**\*.sln'
      platform: 'Any CPU'
      configuration: 'Release'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: '$(solutionPath)/Project1.Test/*.csproj'
      arguments: '-c Release /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=$(Build.SourcesDirectory)/TestResults/Coverage/'
      testRunTitle: 'windows tests'


  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'Azure subscription 1(4a9c4809-c659-4f24-9e67-59d675e2dad7)'
      appType: 'webApp'
      WebAppName: 'Projec1tTest-daniel'
      packageForLinux: '$(System.DefaultWorkingDirectory)/publish'

  - task: PublishCodeCoverageResults@1
    displayName: 'publish code coverage report'
    inputs:
      codeCoverageTool: 'Cobertura'
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/cobertura/coverage.xml'

  - task: SonarCloudAnalyze@1

  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: '300'